config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  get 'articles/:api_id', controller: 'articles', action: 'show', :as => :article
  post 'articles/:api_id/like', controller: 'likes', action: 'create', :as => :article_likes

  root 'articles#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  # This has_many association is a Rails convention
  # to indicate that each Article is associated to many Like records
  # and provides convenient shorthand syntax to access these
  #
  # e.g.
  #
  # `an_article = Article.first`
  # `an_article.likes.count`
  # => 8
  has_many :likes

  # The below scopes permit collections/list of articles to be fetched
  # using shorthand syntax
  # that match particular criteria or appear in a certain order
  #
  # e.g.
  #
  # `Article.by_impressions`
  # returns all articles in order of their api reported impressions count
  scope :published,       -> { where("published_at <= ?", Time.current).order(api_created_at: :desc, api_id: :desc) }
  scope :by_publish_date, -> { order(api_created_at: :desc, api_id: :desc) }
  scope :by_expiry,       -> { order(api_expires_at: :asc) }
  scope :by_updated,      -> { order(api_updated_at: :desc)}
  scope :by_likes,        -> { order(api_like_count: :desc) }
  scope :by_views,        -> { order(api_view_count: :desc) }
  scope :by_impressions,  -> { order(api_impression_count: :desc) }
  scope :by_price,        -> { order(api_views: :desc) }
  scope :by_rating,       -> { order(api_views: :desc) }
  scope :by_distance,     -> { order(api_distance: :asc) }


  # This method returns the most recent local published_at date
  def self.last_checked_at
    maximum(:published_at)
  end

 # This method returns the most recent API-reported updated_at date
  def self.last_updated_at
    maximum(:api_updated_at)
  end


  # The API ID represents
  # the canonical identifier
  # for an article.
  # it must be unique
  validates_uniqueness_of :api_id

  # The API ID represents
  # the public identifier
  # for an article.
  # it is used in URLs
  # The .from_param and #to_param
  # methods enable this employing Rails conventions
  # in conjunction with config/routes.rb and app/controllers/articles_controller.rb
  def self.from_param(needle)
    find_by(api_id: needle)
  end
  def to_param
    api_id.to_s
  end

  # This method combines the count of local application likes
  # with the count of API-reported likes
  #
  # Caveat:
  #
  # In a more complete integration, it is assumed information regarding
  # likes would make it back to the API in some syncrhonisation event
  # and this method would cause double-counting.
  def total_likes
    (likes_count || 0) + (api_like_count || 0)
  end

end

app/models/article_synchronisation_change_log.rb
class ArticleSynchronisationChangeLog
  belongs_to :synchronisation_event
  belongs_to :article
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :article, counter_cache: true, touch: true
end

app/models/synchronisation_event.rb
class SynchronisationEvent < ApplicationRecord
  has_many :article_synchronisation_change_logs

  scope :completed, -> { where("completed_at <= ?", Time.current).order(completed_at: :desc) }

end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles or /articles.json

  # @todo
  # Add Pagination

  # @todo
  # Add Sorting

  # @todo
  # Add Filtering

  # @todo
  # Protect API and app from overzealous fetches due to site popularity
  # Background record updates only
  # e.g.
  # - authenticated postback route from API source to trigger synchronisation
  # - periodic background fetching by app polling

  # @todo
  # Realtime updates to list using turbo streams
  # For Like Count change, For background Article attribute change, etc.

  def index
    # Per requirement, this method refreshes its article store from the API
    # on each request
    # Per @todo above, for DOS resilience and performance, preference is for background
    # updates (not user triggered)
    ArticleSynchroniser.new.sync_and_publish! unless params.has_key?(:allow_stale)
    @articles = Article.published
  end

  def show
    @article = Article.from_param(params.require(:api_id))
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_article

  def create
    @article.likes.create!
    # @todo
    # Determine why redirect_back to index does not update the like count on an article
    # but redirect to article does
    # redirect_back_or_to(url_for(@article))
    redirect_to (url_for(@article))
  end

  private
    def set_article
      @article = Article.from_param(params[:api_id])
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/_article.html.erb
<%
  # @TODO
  # - Move Styling out of html inline style defs
  # - Ensure Semantic html
  # - Improve Accessibility / aria attributes
  # - Add image gallery with lightbox overlay effect
  # - Ensure strings localisation via config/locales and use of t().
  # - Output timezone or match timezone to user locale
  # - Make less ugly
%>

<article id="<%= dom_id article %>" itemscope itemtype="http://schema.org/Article">
  <header>
    <aside>
      <p> Being given away by</p>
      <div itemprop="author publisher" itemscope itemtype="http://schema.org/Organization">
        <a href="<%= article.source.dig('user','current_avatar','original') %>" target='_blank'>
        <img
          alt="Avatar image for user <%= article.source.dig('user','first_name') %>"
          style='aspect-ratio: 1/1; max-height: 100px; object-fit: cover; border-radius: 50%'
          itemprop="image logo"
          srcset="<%= article.source.dig('user','current_avatar','small') %> 100w, <%= article.source.dig('user','current_avatar','large') %> 600w"
          src="<%= article.source.dig('user','current_avatar','small') %>"
        />
        </a>
        <dl>
          <dt>Name</dt>
          <dd itemProp="name"><%= article.source.dig('user','first_name') %><dd>
          <!-- <dt style='display: none'>Roles</dt>
          <dd style='display: none'>
            <% article.source.dig('user','roles')&.each do |role|  %>
              <%= role %>
            <% end %>
          </dd> -->
        </dl>
    </aside>

    <a href="<%= url_for(article) %>"><h2 itemprop="headline"><%= article.title %></h2></a>

    <div class="article-images">
    <% article.source['images']&.each_with_index do |image, ix| %>
      <a href="<%= image['files']['original'] %>" target='_blank'>
        <img src="<%= image['files']['small'] %>"
          alt="Photo (number <%= ix+1 %> of <%= article.source['images'].count %>) showcasing <%= article.title %>"
          srcset="<%= image['files']['small'] %> 80w, <%= image['files']['medium'] %> 300w, <%= image['files']['large'] %> 720w"
          style= "aspect-ratio: <%= image["dimensions"]["width"] %>/<%= image["dimensions"]["height"] %>; max-height: 100px; object-fit: contain"/></a>
    <% end %>

    </div>
    <dl>
      <dt>Description</dt>
      <dd><%= article.source['description'] %></dd>

      <dt>Collection notes</dt>
      <dd><%= article.source['collection_notes'] %></dd>

      <dt>Status</dt>
      <dd><%= article.api_status %></dd>

      <dt>Likes</dt>
      <dd><%= article.total_likes %> <%= render "likes/new", article: article %></dd>

      <dt>Views</dt>
      <dd><%= article.api_view_count %></dd>

      <dt>Impressions</dt>
      <dd><%= article.api_impression_count %></dd>

      <% if article.api_created_at %>
      <dt>Posted</dt>
      <dd><time itemprop="dateCreated datePublished"><%= time_tag article.api_created_at %></time></dd>
      <% end %>

      <% if article.api_expires_at %>
      <dt>Expires</dt>
      <dd> <time itemprop="dateExpires"><%= time_tag article.api_expires_at %></time></dd>
      <% end %>

      <dt>Distance from... maybe you?</dt>
      <dd><%= article.api_distance %> (kilometres? miles? parsecs?)</dd>

    </dl>
  </header>
</article>

app/views/articles/_likes.html.erb
<h2>Likes</h2>

<div id="likes">
  <%#= render article.likes %>
</div>

<%= render "likes/new", article: article %>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Articles</h1>
<dl>
<%- if Article.last_checked_at -%>
<dt>Last checked: </dt>
<dd><%= time_tag Article.last_checked_at %></dd>
<%- end -%>
<%- if Article.last_updated_at -%>
<dt>Last updated:</dt>
<dd><%= time_tag Article.last_updated_at %></dd>
<%- end -%>
</dl>
<div id="articles" data-turbo-permanent>
  <% @articles.each do |article| %>
    <%= render article %>
  <% end %>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>
<button onclick="history.back()">Back</button>
<%= render @article %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Oxenfree</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <meta name="turbo-cache-control" content="no-cache">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/likes/_form.html.erb
<%= form_with(model: like) do |form| %>
  <% if like.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(like.errors.count, "error") %> prohibited this like from being saved:</h2>

      <ul>
        <% like.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/likes/_like.html.erb
<div id="<%= dom_id like %>">
  <%= like.id %> - <%= time_tag like.created_at %>
</div>

app/views/likes/_new.html.erb
<%= form_with model: [ article, Like.new ], html: {:'data-turbo-permanent' => true} do |form|  %>
  <%= form.submit "Like!" %>
<% end %>

app/views/likes/like.html.erb
<div id="<%= dom_id like %>">
  - <%= time_tag like.created_at %>
</div>

app/views/likes/new.html.erb
<h1>New like</h1>

<%= render "form", like: @like %>

<br>

<div>
  <%= link_to "Back to likes", likes_path %>
</div>